// Mock data for Cadence prototype
window.CADENCE_DATA = (function () {
  const D = (y, m, d, h = 0, min = 0) => new Date(y, m, d, h, min);

  const posts = [
    {
      id: '1',
      title: 'Product Launch Announcement',
      content: '🚀 Excited to announce our new AI-powered features! Transform your social media strategy with intelligent automation that learns your voice and audience.',
      platforms: ['x', 'li'],
      status: 'scheduled',
      scheduledDate: D(2026, 4, 28, 10, 0),
      scheduledTime: '10:00',
      hashtags: ['ProductLaunch', 'AI', 'SocialMedia'],
      createdAt: D(2026, 4, 20),
      updatedAt: D(2026, 4, 20),
      metrics: { reach: 12400, engagement: 4.8, clicks: 312 },
    },
    {
      id: '2',
      title: 'Customer Success Story — Sarah',
      content: 'Meet Sarah, who increased her engagement by 300% using our platform. Read her inspiring journey on our blog!',
      platforms: ['fb', 'ig'],
      status: 'scheduled',
      scheduledDate: D(2026, 4, 29, 14, 30),
      scheduledTime: '14:30',
      hashtags: ['CustomerSuccess', 'Growth'],
      createdAt: D(2026, 4, 21),
      updatedAt: D(2026, 4, 21),
    },
    {
      id: '3',
      title: 'Weekly Tips Tuesday',
      content: '💡 Pro Tip: Post during peak engagement hours to maximize reach. Our AI analyzes your audience and suggests the best times to post!',
      platforms: ['x', 'li', 'fb'],
      status: 'scheduled',
      scheduledDate: D(2026, 4, 26, 9, 0),
      scheduledTime: '09:00',
      hashtags: ['TipTuesday', 'SocialMediaTips', 'Marketing'],
      createdAt: D(2026, 4, 22),
      updatedAt: D(2026, 4, 22),
    },
    {
      id: '4',
      title: 'Behind the Scenes',
      content: 'A sneak peek at our team working on exciting new features! Stay tuned for updates. 👀',
      platforms: ['ig'],
      status: 'draft',
      hashtags: ['BehindTheScenes', 'TeamWork'],
      createdAt: D(2026, 4, 23),
      updatedAt: D(2026, 4, 23),
    },
    {
      id: '5',
      title: 'Monday Motivation',
      content: '🌟 Start your week right! Success is not about being the best, it\'s about being better than you were yesterday.',
      platforms: ['li', 'x'],
      status: 'published',
      scheduledDate: D(2026, 4, 25, 8, 0),
      scheduledTime: '08:00',
      hashtags: ['MondayMotivation', 'Success'],
      createdAt: D(2026, 4, 24),
      updatedAt: D(2026, 4, 25),
      metrics: { reach: 8240, engagement: 5.6, clicks: 187 },
    },
    {
      id: '6',
      title: 'Feature Highlight: AI Captions',
      content: 'Never run out of ideas! Our AI generates engaging captions tailored to your brand voice. Try it now! ✨',
      platforms: ['fb', 'ig', 'li'],
      status: 'scheduled',
      scheduledDate: D(2026, 5, 1, 11, 0),
      scheduledTime: '11:00',
      hashtags: ['AIContent', 'ContentCreation', 'Automation'],
      createdAt: D(2026, 4, 23),
      updatedAt: D(2026, 4, 23),
    },
    {
      id: '7',
      title: 'Weekend Engagement Post',
      content: 'Question for you: What\'s your biggest social media challenge? Let us know in the comments! 👇',
      platforms: ['fb', 'x'],
      status: 'draft',
      hashtags: ['Community', 'Engagement'],
      createdAt: D(2026, 4, 24),
      updatedAt: D(2026, 4, 24),
    },
    {
      id: '8',
      title: 'Industry News Share',
      content: '📊 Recent studies show that video content gets 48% more engagement. Time to level up your content strategy!',
      platforms: ['li', 'x'],
      status: 'scheduled',
      scheduledDate: D(2026, 5, 2, 15, 0),
      scheduledTime: '15:00',
      hashtags: ['VideoContent', 'DigitalMarketing'],
      createdAt: D(2026, 4, 25),
      updatedAt: D(2026, 4, 25),
    },
    {
      id: '9',
      title: 'Throwback: Best of Q1',
      content: 'Looking back at our biggest wins from Q1. Thank you to everyone who supported the journey!',
      platforms: ['ig', 'fb'],
      status: 'published',
      scheduledDate: D(2026, 4, 22, 17, 0),
      scheduledTime: '17:00',
      hashtags: ['Throwback', 'Q1Wins'],
      createdAt: D(2026, 4, 22),
      updatedAt: D(2026, 4, 22),
      metrics: { reach: 5120, engagement: 3.9, clicks: 94 },
    },
    {
      id: '10',
      title: 'New Blog: 7 AI Trends for 2026',
      content: 'We broke down the 7 AI trends shaping social marketing this year. Link in bio.',
      platforms: ['x', 'li'],
      status: 'scheduled',
      scheduledDate: D(2026, 4, 27, 13, 30),
      scheduledTime: '13:30',
      hashtags: ['AI', 'BlogPost', 'Trends2026'],
      createdAt: D(2026, 4, 24),
      updatedAt: D(2026, 4, 24),
    },
  ];

  const aiSuggestions = [
    {
      id: 's1',
      title: 'Ask your audience a question',
      content: 'Posts with questions earn 2× more replies on X. Try opening with "What\'s the one tool you can\'t live without?"',
      tag: 'Engagement',
      platforms: ['x', 'fb'],
    },
    {
      id: 's2',
      title: 'Ride the AI-in-marketing wave',
      content: 'Trending on LinkedIn this week. A "5 ways AI changed our team in 30 days" post would land well with your audience.',
      tag: 'Trend',
      platforms: ['li'],
    },
    {
      id: 's3',
      title: 'Feature a customer story',
      content: 'You haven\'t shared user-generated content in 18 days. Spotlight Sarah\'s 300% growth story across IG + FB.',
      tag: 'Idea',
      platforms: ['ig', 'fb'],
    },
  ];

  const activity = [
    { id: 'a1', type: 'publish', text: 'Monday Motivation published to LinkedIn, X', time: '12 min ago' },
    { id: 'a2', type: 'ai',      text: 'AI rewrote 3 captions to match your brand voice', time: '38 min ago' },
    { id: 'a3', type: 'schedule',text: 'Marcus scheduled "Industry News Share" for Mon 3:00 PM', time: '2 hr ago' },
    { id: 'a4', type: 'comment', text: 'New comment on "Q1 Throwback" — 24 mentions today', time: '4 hr ago' },
    { id: 'a5', type: 'publish', text: 'Throwback: Best of Q1 published to Instagram, Facebook', time: 'Yesterday' },
  ];

  const accounts = [
    { handle: '@cadence',         platform: 'x',  followers: '24.1K', growth: '+3.2%', status: 'connected' },
    { handle: 'cadence.app',      platform: 'fb', followers: '12.8K', growth: '+1.4%', status: 'connected' },
    { handle: '@cadence.studio',  platform: 'ig', followers: '38.4K', growth: '+5.8%', status: 'connected' },
    { handle: 'Cadence Inc.',     platform: 'li', followers: '9.3K',  growth: '+2.1%', status: 'connected' },
  ];

  return { posts, aiSuggestions, activity, accounts };
})();
